<?php

namespace AppBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNextEvents(){
        $now = new \DateTime('now');

        $query = $this->createQueryBuilder('e')
            ->where('e.date >= :now')
            ->setParameter('now', $now)
            ->orderBy('e.date', 'ASC')
            ->getQuery();

        return $query->getResult();
    }

    public function getPastEvents(){
        $now = new \DateTime('now');

        $query = $this->createQueryBuilder('e')
            ->where('e.date < :now')
            ->setParameter('now', $now)
            ->orderBy('e.date', 'DESC')
            ->getQuery();

        return $query->getResult();
    }
}
