<?php

namespace AppBundle\Repository;

/**
 * PhotoAlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoAlbumRepository extends \Doctrine\ORM\EntityRepository
{
}
